---
name: "Publish to PyPI"

on:
  push:
    tags:
      - "*"

jobs:
  publish_to_pypi:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: 3.7

      - name: Publish to PyPI
        env:
          PYPI_API_KEY: ${{ secrets.PYPI_API_KEY }}
        run: |
          pip install poetry
          poetry publish --build -u __token__ -p $PYPI_API_KEY
